services:
  - type: web
    name: sahayata-board-cjp
    env: node
    plan: free
    region: singapore
    buildCommand: npm run install:server
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
